{% set name = "Flask-Testing" %}
{% set version = "0.8.0" %}
{% set hash_val = "d849bf53eb1ceb09dff6611888588cb60f20238058fb1ebcd917d69febc373e6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d849bf53eb1ceb09dff6611888588cb60f20238058fb1ebcd917d69febc373e6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - flask

test:
  imports:
    - flask_testing
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jarus/flask-testing
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Unit testing for Flask
  doc_url: https://pythonhosted.org/Flask-Testing/
  dev_url: https://github.com/jarus/flask-testing

extra:
  recipe-maintainers:
    - pmlandwehr
