travis:
  secure:
    BINSTAR_TOKEN: mBSEE+v1ZBvypFui0gnkoFPJSMBQZV8VM2R1hYtHlk4RD0vOhB3u0SMcsM9+kPvdIOYysXabyxmrg4EhMX86f5D1fb3ba4qEmPn09D1H1m3+t5G8YKn0JNV2V8I070G2zft0E5gPnTyz0JScPKRBie1yw9E9vw6e+nGokEtMzCrfLa3XyfuTpDY5nQ+xt/FcWjYEO8IN1kFsvV2J08CuShCGk9ajftMu34pkeeZwkI6aTb6JEXTLi4ZD1zIkSIKPBykhmhaqY+iyWLDy42GJngjFkkXmS2lmPUDCf+6DAVj85Ke08bV/7T4ypTwXydlu9FyyDJkuPpDTbz1Nre7hnMpQKx5lz7cwynFdnnM3B++7XnPTzB0NdcT3e/JOjqKamIZ9fHAs4awq0EePegto82SuTOtRwGjbpDt8CksvmjukO8EdTxuv4DcEKxDoI8mJ4m3QAgjfKCrMOnDAjG8JXULWJ82KDNd/kNUTHKKN1pCVUG027CoRNDYId7FvnW2VE3DpK3ISDcluWf48BdIK4dbF4tlICNbnPaYsOxw0NlMs6BME0l0Lt6j11C+zpeuPGupqfdZVlWlZrR8TcMNWTxKvSKz9ev2XujfFQLOjHCSrLHwPue9E6fuogJuAoE4LhpixwYpa0FQq5kRTzVpqEDw+FvKfXZkzrKZe5pRWIgY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
