travis:
  secure:
    BINSTAR_TOKEN: G0ql989mM2hcx1ozi596k6wRbMzrtxMvQw00SWMdtM8OAKon8YThCyewA9RC8tkfN4f23RnectSWgDDyBkSPu0CvM+AHXRFvgeprhb2HGCr/37mng+hmq94R6CteeUqG39cFq8oidGIOsdquY4/WQSEFlM072sWwYxZ5WXnWddn8kFM4USCxv+dHpsK9uhvbpbZOhP4hGgpGmN9lbnxraIPvGX0Ik+fQbFtvdhNNj9/YMHddH+gyxs5XAP+dje4nanDHbg82AEvcvUUn3z06V9GbwPDXGvDzUtTtoDlwBxc7wg7bjCdXC0EEaCaYdZvseryv0Rk0ECu/LiNgQvwyFTo9hvUZU+LZHUjKcXZW4t1b5ZoqAs8Ke+qf3rPso6+nY4R0QijCsD9cL5OzBeRhmTEWPo70tOuIJI5YfcrEXfmlswkFD53onFP259DHE5TE1osAZPr/52C9COAxYWty09vRkHlr3mHtctJJ90+8R28Zmu9FGCltTDDaklGvw+I4vaze6RzftXSYgyiEcHSh40mLrF9nOXYhNWNDMYj2pi5oddmzMfs86gacwskI1hsSzY/CREl8USUIaFx2qk0Z80Cj0rIT4Js7IPEZPmkel9IzrLKBd450JiQJPZ1OgcsdXdn4lVG7AVFvFVYeQvI1hFrMGb4smqb6L/aD1ImjBhU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
