travis:
  secure:
    BINSTAR_TOKEN: JKdJdmE62B1ljLbGTUUAfTAegbfK6CBClZXGdmOG5TBTePyOoeA6QCqEWFZL5G58x2J4uu5myKSaG4YQexnP6lRQMAiaWSpQfUKzXV6y06IwD74WmxNPUHrAUnzhJQZtY0GgaclQe9xDEffXSrn5t2aix4D+SSWHSxMdMk5qOzsj+GVC87wv9LxsOfKbke0cg8ommskxXpsr/YteAzIcTUJkzWoc5bpcfvY/9Hu/UGoW4WIxAKgyWruBTTuUS2rMf8qfTlPXBQ9LV+xbQ64rpKFL7dhnRqutAr/l7QIFNUxWGLmeolIgPDVYG1+wZOwFVaOknDqGv6GEiQ5itWT/gw/gRjnZIz5b0CTJkeCY/Y6Y7VQbbb1a2uepY6xjwyTGl4C5WybbifSi/NPB8tGeqDNEyRX/JaFKM1/wzsP4k1dKmuQ7ZsCJ2qUfs6rgrE5Yxs5wVQW1m8GtNTupQaDQTZC1uMxU9XwQ4exf1eu9ZwBcWUsZ2hq3703TJyAbV9mDFpCeA8D94g0fWLdoOqhQUbHgtK2p8tpWj26Uk9PT93x5FAmujb6JpP0bj2hOspS5DZi9Ety5NR8zT4FxJES0HFfm6AVJdzjSd37V686oU3M0DgRu/Fn4IWvTC2AwBKG6de2GN3WudlsZD8RZHuvb0s5NZECwr4RAY1RGKmrxWnM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
