travis:
  secure:
    BINSTAR_TOKEN: Mb6rnAl/BY8jlw2ETs/Tfl76RcXsSfN2FXZb0GP5nKTRbipXBLmMWoL5bDmSqeMRtEHUkpc6NwqvdgKbWuwi4NfDsavWpX3d1nhEzGu2sMB4AV/Tl4UKrSobbIgxaam7Y7HR9S3WmvgKILSn8b+4bNJ5Src7bCcFCQ7dz8qDK1qPW7919QEUk1ACHkgcU4BAqqPZ/8Hum1xsH+QfASlqEjv1YhDrbKqfsoWCd0C+vJaUKzhrrFgEo6lLOTRYwsjX/nYv8lELxbM32IEtqMqtPE0lrvb7a+ndp4XXsp8b+epZReGM+biRjp5+LSmn6/UNWLR45gMvtBY0l3dh26LBzL9SPrwxUSrDdefAdfPLu7ZtNzFEnt2pVwNB4Ilvbj4pCXNsIFPpp8hV+y4LjHsfxPCDs+o1qSNnaQF78ux9Se+AtUTNWhXZ5I5nMFfbPwj6f3u17fN+D4HBJ8fIArkGuH/c1FqYhZ5JOFrLeqS0pudD4HlBrCtkaXbfS3FJxkBbE7Be0V9fSWrRj6792NXWmZRYCrCxGtvBJbJpdw4Thh2osYUVw5XiFJtBTC1sbaimD1jiNxuVRXroFnrbXm/OzA7oc8MD3JcJmGCclR77oJkcXO3Rra5jbMw9GeeJXSiy6PWUxRZCCJ9HaaTSwnLeGXccnc0m+bpKcMiVqNHgYBA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
